# Generated by Django 3.1.6 on 2021-03-05 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Лист',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('created_date', models.DateField(verbose_name='Дата создания')),
                ('due_on', models.DateField(verbose_name='Дата оканчания')),
                ('owner', models.CharField(blank=True, max_length=255, null=True, verbose_name='Владельец')),
                ('mark', models.BooleanField(verbose_name='Статус')),
                ('todos', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='todos', to='main.todos', verbose_name='Лист')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
