# Generated by Django 3.1.6 on 2021-03-05 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210305_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 5, 13, 34, 48, 833346), verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='due_on',
            field=models.DateField(default=datetime.datetime(2021, 3, 5, 13, 34, 48, 833346), verbose_name='Дата оканчания'),
        ),
    ]
