# Generated by Django 3.1.6 on 2021-03-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210305_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todos',
            options={'verbose_name': 'Лист', 'verbose_name_plural': 'Листы'},
        ),
    ]
